# Generated by Django 2.2.5 on 2019-09-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebookapp', '0002_telefon_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telefon_Mail',
        ),
    ]
