# Generated by Django 2.2.5 on 2019-09-02 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebookapp', '0003_delete_telefon_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='osoba',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='phonebookapp.Osoba'),
        ),
        migrations.AlterField(
            model_name='telefon',
            name='osoba',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='telefon', to='phonebookapp.Osoba'),
        ),
    ]
